server:
  port: 9999
  servlet:
    context-path: /ems



# spring???? datasource???  thymeleaf ????
spring:

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ems?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
  web:
    resources:
      static-locations: classpath:/static/,file:${photo.file.dir} #暴露出哪些资源可以通过项目名访问



# mybatis配置
mybatis:
  mapper-locations: classpath:com/program/mapper/*.xml
  type-aliases-package: com.program.entity

# 日志配置
logging:
  level:
    root: info
    com.program: debug


# 指定文件上传位置
photo:
  file:
    dir: D:\JavaProgram06\ems\photo
